#!/usr/bin/env node
/* Writes src/figures/index.js from every figure file under src/figures/.
   Skips index.js and any file or folder whose name starts with "_".
   Usage: node scripts/registry.mjs */
import { readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../src/figures/", import.meta.url));

function walk(dir) {
  const out = [];
  for (const f of readdirSync(dir).sort()) {
    if (f.startsWith("_") || f.startsWith(".")) continue;
    const p = join(dir, f);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (f.endsWith(".js") && f !== "index.js") out.push(p);
  }
  return out;
}

const files = walk(root.replace(/\/$/, ""));
const ident = (p) => basename(p, ".js").replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const seen = new Set();
const lines = files.map((p) => {
  const id = ident(p);
  if (seen.has(id)) throw new Error(`registry: two figures named ${id} (${relative(root, p)})`);
  seen.add(id);
  return `export { default as ${id} } from "./${relative(root, p)}";`;
});

writeFileSync(
  join(root, "index.js"),
  `/* Generated by scripts/registry.mjs. Do not edit by hand: add a file under
   src/figures/<shelf>/ and run \`npm run registry\`. */
${lines.join("\n")}
`,
);
console.log(`registry: ${files.length} figure${files.length === 1 ? "" : "s"} -> src/figures/index.js`);
